import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { createSupabaseServer } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { headers } from "next/headers";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Record<string, string>;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          josefinSans.className,
          "flex w-full min-h-screen bg-black text-white antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
